---
meta:
  engine: 4.1.0
  version: 0.0.1
  author: Amandeep Singh (@amandeepsp)
units:
  # Proxy spacing variables
  kx: cx
  ky: cy
  # Padding variables
  px: kx + 2
  py: ky + 2
points:
  zones:
    matrix:
      columns:
        outers:
        pinky:
        ring:
        middle:
        index:
        inner:
      rows:
        mod:
        bottom:
        home:
        top:
        num:
